package sk.juleni.model;

import java.io.Serializable;

public abstract class DataObject implements Serializable {
    // Constants ////////////////////////////////////////////////////////////////

    /**
     * ID used when creating new object for which the real ID wasn't generated yet.
     * HSQLDB at some time autogenerated first entry as 0 and it wasn't possible
     * to change it. Therefore we used -1 as value which won't be generated by DB.
     * Then HSQLDB made it configurable but I was afraid that -1 was already used
     * at some places as hardcoded value and not at constant that it is too risky
     * to change it to 0 (which is what would it be if the value it not initialized)
     */
    public static final Long NEW_ID = -1L;

    /**
     * String representation for easy reuse.
     */
    public static final String NEW_ID_STR = Long.toString(NEW_ID);

    // Attributes ///////////////////////////////////////////////////////////////

    /**
     * Flag which is set to true if this data was loaded from some persistance
     * store, e.g. database and false if it was constructed in memory and it is
     * not persisted.
     */
    private boolean m_bFromPersistanceStore = false;

    // Accessors ////////////////////////////////////////////////////////////////

    /**
     * Check if this record was loaded from some persistence store  and therefore
     * it is existing data object which was already created in the persistence
     * store or it came from somewhere else (was created in memory).
     *
     * @return boolean
     */
    public boolean isFromPersistenceStore(
    )
    {
        return m_bFromPersistanceStore;
    }

    /**
     * Set flag that this record was loaded from some persistance store.
     */
    public void setFromPersistenceStore(
    )
    {
        m_bFromPersistanceStore = true;
    }
}